# Generated by Django 5.1.6 on 2025-03-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garment",
            name="detected_symbols",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="garment",
            name="image",
            field=models.ImageField(upload_to="media/garment_labels/"),
        ),
    ]
